name: check secrets manager

on:
  push:
    branches:
      - '*'

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: access_token
        workload_identity_provider: 'projects/456501578714/locations/global/workloadIdentityPools/github-actions-sm-demo/providers/github'
        service_account: 'secret-manager@celtic-music-434007-r1.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Access Secret    
      run: |-
        gcloud secrets versions access "latest" --secret mysct
    #     - id: 'secrets'
    #   uses: 'google-github-actions/get-secretmanager-secrets@v2'
    #   with:
    #     secrets: |-
    #         token:456501578714/mysct
    # - id: 'publish'
    #   run: echo hi
    #   env:
    #     TOKEN: '${{ steps.secrets.outputs.token }}'
  