name: check secrets manager

on:
  push:
    branches:
      - '*'

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/456501578714/locations/global/workloadIdentityPools/github-actions-sm-demo/providers/github'
        service_account: 'secret-manager@celtic-music-434007-r1.iam.gserviceaccount.com'
    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with:
        secrets: |-
            token:projects/456501578714/secrets/mysct/versions/1
    - id: 'publish'
      run: echo hi
      env:
        TOKEN: '${{ steps.secrets.outputs.token }}'
