name: CI/CD with Ansible to GCP Compute Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: app.jar
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v3
      with:
        name: app.jar

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Set up Ansible Inventory
      run: |
        echo '[gce_instance]' > inventory.ini
        echo "${{ secrets.GCE_INSTANCE_IP }}" >> inventory.ini

    - name: Deploy Application with Ansible
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
      run: |
        ansible-playbook -i inventory.ini deploy.yml
