name: CI/CD with Ansible to GCP Compute Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: app.jar
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download JAR artifact
      uses: actions/download-artifact@v3
      with:
        name: app.jar

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible
    - name: Display content
      run: |
        pwd
        ls

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        inventory: inventory.ini
        key: ${{ secrets.SSH_PRIVATE_KEY }}